### ISSUE TITLE
Availability of OTU sequences

### ISSUE THREAD

**Issue by BenBeresfordJones** [jlleslie/AdaptiveImmunity_and_Clearance#1]
Dear Jhansi Leslie,

By any chance have you made the representative OTU sequences from you analyses available? I am interested in the identity of OTU52 and OTU93 that you commented on in your paper (mSphere 2019). If these sequences are not already available, would you kindly be willing to share them with me?

Apologies if I have missed their availability already on this GitHub.

Best wishes,
Benjamin

**Comment by jlleslie** [comment]
Hi apologies for the delayed response, raw reads for the study can be accessed here : https://www.ncbi.nlm.nih.gov/bioproject/PRJNA388335

**Comment by jlleslie** [comment]
>M00967_70_000000000-A6G18_1_1101_28214_16445	Otu0052|129
TAC---GT-AG-GTG----GCA-A-G--C--G--T--T--AT-C-CGG-AA---TT-A--T-T--GG-GC---GT-A----AA-GG-GA-GC----G-TA-G-A-C-G--------G--T-GC-A-G-C---AA--G-T-C-T---G-A-T--G--TG--A-AA-GG--T-C-GG-G-G-----------CC-C-AA---C-C-C-C-G-G-G-A-C-T-G--C-A--T-T--G--GA-A-A--C-T--G-T--TG--A-A-C-T-G-G-A-G-T-A---C-AG---GA-G-A---G-G-T-A---AG-C---GG--A--ATT--------------------------C-C-T-A-GT--GT-A-G-CG-GT-G-A-A-A--TG-C-GT-AG--AT-A-TT-------------------A-G-G-A-G-G-A-AC-A-CC---AG--T-G--GC-GAA-G-G-C--G-G--C-T-T-A---CTG--G--AC-T-G--T-A--A-C-T--GA--CG--T-T-G--A-GG--C-T-CG-A--AA-G-C--G-TG--GG-G--AG-C-A-AA--CA-GG


>M00967_70_000000000-A6G18_1_1102_28599_20327	Otu0093|139
TAC---GT-AG-GGG----GCA-A-G--C--G--T--T--AT-C-CGG-AT---TT-A--C-T--GG-GT---GT-A----AA-GG-GA-GC----G-TA-G-A-C-G--------G--C-CG-T-G-C---AA--G-T-C-T---G-A-A--G--TG--A-AA-TG--C-C-GG-G-G-----------CT-C-AA---C-C-C-C-G-G-A-A-C-T-G--C-T--T-T--G--GA-A-A--C-T--G-T--AC--A-G-C-T-A-G-A-G-T-G---C-AG---GA-G-G---G-G-T-G---AG-C---GG--A--ATT--------------------------C-C-T-A-GT--GT-A-G-CG-GT-G-A-A-A--TG-C-GT-AG--AT-A-TT-------------------A-G-G-A-G-G-A-AC-A-CC---GG--T-G--GC-GAA-G-G-C--G-G--C-T-C-A---CTG--G--AC-T-T--T-A--A-C-T--GA--CG--T-T-G--A-GG--C-T-CG-A--AA-G-C--G-TG--GG-G--AG-C-A-AA--CA-GG

**Comment by jlleslie** [comment]
0.03 cut off

**Comment by BenBeresfordJones** [comment]
Thank you! This is really helpful.

**Comment by BenBeresfordJones** [comment]
Highly appreciate it.
